ExUnit.start()
Mimic.copy(Anthropix)
Mimic.copy(Japanese.Corpus.StorageLayer)
Mimic.copy(Japanese.Corpus.Story)
Mimic.copy(Japanese.Corpus.Page)
Mimic.copy(Japanese.Translation)
Mimic.copy(Japanese.Translation.Service)
